(load-library "~/src/emacs-module-postgres/pq.so")
(setq con (pq:connectdb "port=5433 dbname=smith"))
(setq result (pq:exec con "select version()"))
(pq:ntuples result)
(pq:nfields result)
(pq:getvalue result 0 0)
(setq result (pq:exec con "select version(),now()"))
(pq:getvalue result 0 1)
(pq:getvalue (pq:execParams con "select 'Hello, ' || $1::text" (user-login-name)) 0 0)
(pq:escapeLiteral con "moo'oo")
(pq:exec con (concat "set application_name to " (pq:escapeLiteral con (emacs-version))))
(setq result (pq:exec con "select version()"))
(setq result (pq:exec con "select * from pg_stat_activity"))
(pq:getrow result 0)
(setq con nil)
(garbage-collect)
